server:
  port: 8081

spring:
  application:
    name: mytest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/course?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: love3224

#mybatis:
#  mapper-locations:
#    - mapping/sqlMapper.xml
#  type-aliases-package: com.course.entity
#  configuration:
#    map-underscore-to-camel-case: true

